apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: course-app-production
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: production
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./overlays/production"
  prune: true
  timeout: 1m
  dependsOn:
    - name: dragonfly-operator